name : Deploy ON Push

ON :
  Push:
    branches:
      - main

jobs:
  check:
    runs-on: ubunto-latest
      step:
        - name: Testing
          run: |
            echo "Testing CI/CD pipeline"
            echo "Testing CI/CD pipeline 2"
                